# Generated by Django 4.0 on 2025-03-15 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('eventapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='assigned_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_orders', to='auth.user'),
        ),
        migrations.AddField(
            model_name='booking',
            name='price_quote',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', '待确认报价'), ('quoted', '待支付'), ('paid', '已支付'), ('cancelled', '已取消')], default='pending', max_length=10),
        ),
    ]
