# Generated by Django 4.0 on 2025-03-17 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('eventapp', '0002_booking_assigned_manager_booking_price_quote_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventservice',
            name='default_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='booking',
            name='assigned_manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_orders', to='auth.user'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.CharField(choices=[('pending', '待确认报价'), ('assigned', '已接单'), ('quoted', '待支付'), ('paid', '已支付'), ('cancelled', '已取消')], default='pending', max_length=10),
        ),
    ]
