# Generated by Django 4.0 on 2025-04-07 18:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventapp', '0004_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='payment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booking_payment', to='eventapp.payment'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='booking',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payment_record', to='eventapp.booking'),
        ),
    ]
